'use client'

import {
  AlertTriangle,
  ArrowRight,
  Bell,
  Phone,
  Sprout,
} from 'lucide-react'

import type { AppRouter } from '@/lib/navigation'

import { PageHeader } from '@/components/layout/PageHeader'

import { Button } from '@/components/ui/button'

import { StatusBadge } from '@/components/ui/status-badge'

import { getCropCheckState } from '@/lib/crop-check-store'

import { useEffect, useState } from 'react'

type AnalysisResult = {
  scan_id?: number
  crop?: string
  city?: string
  disease?: string
  confidence?: number
  confidence_percent?: number
  image_url?: string
  temperature?: number
  humidity?: number
  risk_level?: string
  risk_score?: number
  overall_status?: string
  recommendation?: string
  action?: string
  warning?: string
}

export function Advisory({
  router,
}: {
  router: AppRouter
}) {
  const [result, setResult] =
    useState<AnalysisResult | null>(null)

  useEffect(() => {
    const session = getCropCheckState()

    if (session.result) {
      setResult(
        session.result as AnalysisResult
      )
    }
  }, [])

  function handleExpertHelp() {
    if (!result) {
      alert(
        'No crop analysis report found. Please perform a Crop Check first.'
      )

      return
    }

    const crop =
      result.crop || 'Unknown crop'

    const disease =
      result.disease || 'Unknown disease'

    const city =
      result.city || 'Nashik'

    const confidence =
      result.confidence_percent ??
      Math.round(
        (result.confidence ?? 0) * 100
      )

    const riskLevel =
      result.risk_level || 'Unknown'

    const riskScore =
      result.risk_score !== undefined
        ? `${Math.round(
            result.risk_score * 100
          )}%`
        : 'N/A'

    const temperature =
      result.temperature !== undefined
        ? `${result.temperature}°C`
        : 'N/A'

    const humidity =
      result.humidity !== undefined
        ? `${result.humidity}%`
        : 'N/A'

    const report = `🌱 CROP HEALTH REPORT

━━━━━━━━━━━━━━━━━━
🌾 CROP DETAILS
━━━━━━━━━━━━━━━━━━

Crop: ${crop}
Location: ${city}

━━━━━━━━━━━━━━━━━━
🦠 DISEASE ANALYSIS
━━━━━━━━━━━━━━━━━━

Disease detected: ${disease}

Detection confidence: ${confidence}%

━━━━━━━━━━━━━━━━━━
🌦️ ENVIRONMENTAL CONDITIONS
━━━━━━━━━━━━━━━━━━

Temperature: ${temperature}
Humidity: ${humidity}

━━━━━━━━━━━━━━━━━━
⚠️ RISK ASSESSMENT
━━━━━━━━━━━━━━━━━━

Risk level: ${riskLevel}
Risk score: ${riskScore}

━━━━━━━━━━━━━━━━━━
📋 OVERALL STATUS
━━━━━━━━━━━━━━━━━━

${result.overall_status || 'N/A'}

━━━━━━━━━━━━━━━━━━
✅ RECOMMENDED ACTION
━━━━━━━━━━━━━━━━━━

${result.action || 'N/A'}

━━━━━━━━━━━━━━━━━━
💡 RECOMMENDATION
━━━━━━━━━━━━━━━━━━

${result.recommendation || 'N/A'}

━━━━━━━━━━━━━━━━━━
⚠️ WARNING
━━━━━━━━━━━━━━━━━━

${result.warning || 'N/A'}

━━━━━━━━━━━━━━━━━━
🆔 SCAN INFORMATION
━━━━━━━━━━━━━━━━━━

Scan ID: ${result.scan_id ?? 'N/A'}

Analyzed image:
${result.image_url || 'Image link unavailable'}

━━━━━━━━━━━━━━━━━━

Hello, I need expert agricultural guidance regarding this crop disease analysis.

Please review the above report and advise me on the appropriate next steps.

Generated by Crop Health Assistant.`

    const whatsappUrl =
      `https://wa.me/918006889697?text=${encodeURIComponent(
        report
      )}`

    window.open(
      whatsappUrl,
      '_blank',
      'noopener,noreferrer'
    )
  }

  return (
    <>
      <PageHeader
        eyebrow="CROP ADVISORY"
        title="Crop advisory"
        subtitle="Simple next steps for your crop."
        action={
          <StatusBadge tone="red">
            HIGH PRIORITY
          </StatusBadge>
        }
      />

      <div className="advisory-grid">

        <section className="card now-card">

          <div className="advisory-title">

            <span className="recommendation-icon">
              <Sprout />
            </span>

            <div>

              <p className="eyebrow">
                WHAT TO DO NOW
              </p>

              <h2>
                Protect your crop
              </h2>

            </div>

          </div>

          <ol>

            <li>
              <span>1</span>

              <p>
                Inspect nearby plants for similar symptoms.
              </p>
            </li>

            <li>
              <span>2</span>

              <p>
                Remove severely affected plant material where appropriate.
              </p>
            </li>

            <li>
              <span>3</span>

              <p>
                Monitor field humidity and moisture.
              </p>
            </li>

            <li>
              <span>4</span>

              <p>
                Follow locally approved integrated pest management guidance.
              </p>
            </li>

          </ol>

          <p className="safety-note">

            <AlertTriangle />

            Always follow locally approved agricultural guidance and product label instructions.

          </p>

        </section>

        <aside className="advisory-side">

          <section className="card next-check">

            <p className="eyebrow">
              NEXT CHECK
            </p>

            <h2>
              Inspect again in 2 days
            </h2>

            <p>
              Look for new spots on lower leaves and compare with this result.
            </p>

            <Button
              className="primary-button full"
              onClick={() => {
                alert(
                  'Reminder feature can be connected next.'
                )
              }}
            >

              <Bell data-icon="inline-start" />

              Set reminder

            </Button>

          </section>

          <section className="card expert">

            <Phone />

            <div>

              <h3>
                Need expert help?
              </h3>

              <p>
                Talk with an agricultural extension expert.
              </p>

            </div>

            <button
              type="button"
              aria-label="Contact extension expert on WhatsApp"
              onClick={handleExpertHelp}
            >
              <ArrowRight />
            </button>

          </section>

        </aside>

      </div>
    </>
  )
}